services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${DATASOURCE_DB}
      - POSTGRES_USER=${DATASOURCE_USER}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    ports:
      - '${DATASOURCE_PORT}:${DATASOURCE_PORT}'
