###
GET http://localhost:8080/v1/api/expenses

###
GET http://localhost:8080/v1/api/expenses/1

###
POST http://localhost:8080/v1/api/expenses
Content-Type: application/json

{
  "description": "Test Expense",
  "amount": 100,
  "transactionDate": "2023-10-01"
}

###
POST http://localhost:8080/v1/api/expenses
Content-Type: application/json

{
  "description": "Test Expense",
  "amount": 100,
  "transactionDate": "2023-10-01",
  "categoryId": 2
}

###
DELETE http://localhost:8080/v1/api/expenses/1


###
GET http://localhost:8080/v1/api/categories

###
GET http://localhost:8080/v1/api/categories/2

###
POST http://localhost:8080/v1/api/categories
Content-Type: application/json

{
  "name": "Test Category"
}

###
POST http://localhost:8080/v1/api/categories
Content-Type: application/json

{
  "name": "Uncategorized"
}

###
PUT http://localhost:8080/v1/api/categories/2
Content-Type: application/json

{
  "name": "Updated Category"
}

###
DELETE http://localhost:8080/v1/api/categories/2
